### PR TITLE
Non-interactive update + prune images

### PR DESCRIPTION
**Pull request by sylvainbx**
Retrieve these interesting changes from the jakeswenson repo:
- ability to run the update non-interactively with some command-line parameters
- pruning the docker images after the update, to free some disk space

### CODE REVIEW

**Comment by alexyao2015** [comment]
Update bitwarden isn't being used here, so those changes wouldn't work here. Both have been replaced by patch-bitwarden

**Comment by alexyao2015** [comment]
Bitwarden.sh also runs docker prune so there's no need for docker prune here.

**Comment by sylvainbx** [comment]
Ok, maybe I can extract only the "non-interactive" part and create a new pull request for this on `patch-bitwarden.sh` ?

**Comment by alexyao2015** [comment]
Sure! Would you also apply the patches to patch-bitwarden-custom.sh as well? I also noticed the patches from #2 were not applied there either.

**Pull request closed without merging**
