### PR TITLE
Using Mono.Cecil to enable SecretsManager functionality to CustomPlan

### PR DESCRIPTION
**Pull request by nielscil**
Initialize the SecretsManager property on CustomPlan using Mono.Cecil so that CustomPlan can also use the SecretsManager, see screenshot of ILSpy (don't mind my terrible paint skills): 

image

### CODE REVIEW

**Comment by nielscil** [comment]
I've tested it with my selfhosted client and it looks fine now

**Comment by alexyao2015** [comment]
This seems oddly prone to breaking and requiring maintenance as the code changes upstream.

**Comment by alexyao2015** [comment]
I created a PR to update the license to enterprise since its much less likely to break in the future (there has already been a refactor that breaks this). Secrets manager works on my instance with this new license. Can you test this and confirm?

**Comment by nielscil** [comment]
I do agree with you but I didn't know what the consequences are for the password manager when changing the plan to enterprise. Do we know it doesn't break anything? I'm thinking of amount of seats, storage etc?

I currently haven't got the time to test it. Will do when I've got some time.

**Comment by nielscil** [comment]
The enterprise plan seems to be working good and is more robust way.

**Pull request closed without merging**
